package com.example.myapplication.search.bean.bilibili

import java.io.Serializable

data class VideoBySearch(
    val type: String?,
    val id: Long?,
    val author: String?,
    val mid: Long?,
    val typeid: String?,
    val typename: String?,
    val arcurl: String?,
    val aid: Long?,
    val bvid: String?,
    val title: String?,
    val description: String?,
    val arcrank: String?,
    val pic: String?,
    val play: Long?,  // 根据上下文，可能是可为空类型
    val video_review: Int?,
    val favorites: Int?,
    val tag: String?,
    val review: Int?,
    val pubdate: Long?,
    val senddate: Long?,
    val duration: String?,
    val badgepay: Boolean?,
    val hit_columns: List<String?>,
    val view_type: String?,
    val is_pay: Int?,
    val is_union_video: Int?,
    val rec_tags: Any?,
    val new_rec_tags: List<Any>?,
    val rank_score: Long?,
    val like: Int?,
    val upic: String?,
    val corner: String?,
    val cover: String?,
    val desc: String?,
    val url: String?,
    val rec_reason: String?,
    val danmaku: Int?,
    val biz_data: Any?, // 根据需要调整类型
    val is_charge_video: Int?,
    val vt: Int?,
    val enable_vt: Int?,
    val vt_display: String?,
    val subtitle: String?,
    val episode_count_text: String?,
    val release_status: Int?,
    val is_intervene: Int?,
    val area: Int?,
    val style: Int?,
    val cate_name: String?,
    val is_live_room_inline: Int?,
    val live_status: Int?,
    val live_time: String?,
    val online: Int?,
    val rank_index: Int?,
    val rank_offset: Int?,
    val roomid: Long?,
    val short_id: Int?,
    val spread_id: Int?,
    val tags: String?,
    val uface: String?,
    val uid: Long?,
    val uname: String?,
    val user_cover: String?,
    val parent_area_id: Int?,
    val parent_area_name: String?,
    val watched_show: WatchedShow?
) : Serializable

